from pathlib import Path
import re

from PIL import Image, ImageDraw


REPO_ROOT = Path(__file__).resolve().parents[2]
SKINS_DIR = REPO_ROOT / "skins"
OUT_FILE = REPO_ROOT / "flappy-bird" / "src" / "rtl" / "display" / "bird_sprite_rom.v"

SPRITE_W = 21
SPRITE_H = 21
MAX_FRAMES = 8
ALPHA_THRESHOLD = 32


def frame_number(path: Path) -> int:
    match = re.search(r"(\d+)", path.stem)
    return int(match.group(1)) if match else 0


def draw_original_frame(path: Path, wing_offset: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img = Image.new("RGBA", (SPRITE_W, SPRITE_H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    top = 2
    left = 0
    width = 21
    height = 16

    d.rectangle([left, top, left + width - 1, top + height - 1], fill=(255, 221, 0, 255))
    d.rectangle([left, top, left + width - 1, top + height - 1], outline=(0, 0, 0, 255))
    d.rectangle([5, top + 7 + wing_offset, 11, top + 10 + wing_offset], fill=(221, 136, 0, 255))
    d.rectangle([16, top + 6, 20, top + 9], fill=(255, 102, 0, 255))
    d.rectangle([14, top + 3, 16, top + 5], fill=(255, 255, 255, 255))
    d.point((15, top + 4), fill=(0, 0, 0, 255))
    img.save(path)


def ensure_original_skin() -> None:
    original_dir = SKINS_DIR / "original" / "frames_21x21"
    offsets = [0, 1, 2, 1, 0, -1]
    for index, offset in enumerate(offsets):
        draw_original_frame(original_dir / f"frame_{index}_21x21.png", offset)
    readme = SKINS_DIR / "original" / "README.txt"
    readme.write_text(
        "Original procedural bird skin exported as 21x21 PNG frames.\n"
        "Collision still uses the 21x16 hitbox in collision.v.\n",
        encoding="utf-8",
    )


def list_frame_files(skin_dir: Path) -> list[Path]:
    candidates: list[Path] = []
    for subdir in sorted(skin_dir.glob("frames*")):
        if subdir.is_dir():
            candidates.extend(sorted(subdir.glob("*.png"), key=frame_number))
    if not candidates:
        candidates.extend(sorted(skin_dir.glob("frame*.png"), key=frame_number))
    if not candidates:
        # 支持 Sprite1.png、bird_01.png 等根目录连续图片；预览图/sheet 不作为动画帧。
        for image in sorted(skin_dir.glob("*.png"), key=frame_number):
            name = image.stem.lower()
            if "preview" in name or "sheet" in name:
                continue
            candidates.append(image)
    return candidates[:MAX_FRAMES]


def load_frame(path: Path) -> list[tuple[int, int, int]]:
    img = Image.open(path).convert("RGBA")
    src_w, src_h = img.size
    if src_w > SPRITE_W or src_h > SPRITE_H:
        img.thumbnail((SPRITE_W, SPRITE_H), Image.Resampling.NEAREST)
        src_w, src_h = img.size

    left_pad = (SPRITE_W - src_w) // 2
    top_pad = (SPRITE_H - src_h) // 2
    pixels: list[tuple[int, int, int]] = []

    for y in range(SPRITE_H):
        for x in range(SPRITE_W):
            sx = x - left_pad
            sy = y - top_pad
            if 0 <= sx < src_w and 0 <= sy < src_h:
                r, g, b, a = img.getpixel((sx, sy))
                if a >= ALPHA_THRESHOLD:
                    rgb444 = ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)
                    pixels.append((x, y, rgb444))
    return pixels


def discover_skins() -> list[tuple[str, list[Path]]]:
    ensure_original_skin()
    skin_dirs = [p for p in SKINS_DIR.iterdir() if p.is_dir()]
    skin_dirs.sort(key=lambda p: (0 if p.name == "original" else 1, p.name.lower()))

    skins: list[tuple[str, list[Path]]] = []
    for skin_dir in skin_dirs:
        frames = list_frame_files(skin_dir)
        if frames:
            skins.append((skin_dir.name, frames))
    if not skins:
        raise SystemExit("No skin frames found.")
    return skins


def emit_rom(skins: list[tuple[str, list[Path]]]) -> None:
    total_skins = len(skins)
    pixels_per_frame = SPRITE_W * SPRITE_H
    total_pixels = total_skins * MAX_FRAMES * pixels_per_frame
    lines: list[str] = []

    lines.append("`timescale 1ns / 1ps")
    lines.append("")
    lines.append("// Generated by flappy-bird/tools/generate_skin_rom.py.")
    lines.append("// Sprite display size is 21x21. Source frames may be 1..8 frames per skin.")
    lines.append("module skin_info(")
    lines.append("    input  wire [2:0] skin_id,")
    lines.append("    output reg  [3:0] frame_count")
    lines.append(");")
    lines.append("    always @(*) begin")
    lines.append("        case (skin_id)")
    for index, (name, frames) in enumerate(skins):
        lines.append(f"            3'd{index}: frame_count = 4'd{len(frames)}; // {name}")
    lines.append("            default: frame_count = 4'd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("endmodule")
    lines.append("")
    lines.append("module bird_sprite_rom(")
    lines.append("    input  wire [2:0] skin_id,")
    lines.append("    input  wire [2:0] frame_index,")
    lines.append("    input  wire [4:0] sprite_x,")
    lines.append("    input  wire [4:0] sprite_y,")
    lines.append("    output reg        alpha,")
    lines.append("    output reg [11:0] rgb")
    lines.append(");")
    lines.append(f"    localparam integer SKIN_COUNT = {total_skins};")
    lines.append(f"    localparam [2:0] SKIN_COUNT_VALUE = 3'd{total_skins};")
    lines.append(f"    localparam integer MAX_FRAMES = {MAX_FRAMES};")
    lines.append(f"    localparam integer SPRITE_W = {SPRITE_W};")
    lines.append(f"    localparam [4:0] SPRITE_W_VALUE = 5'd{SPRITE_W};")
    lines.append(f"    localparam integer SPRITE_H = {SPRITE_H};")
    lines.append(f"    localparam [4:0] SPRITE_H_VALUE = 5'd{SPRITE_H};")
    lines.append("    localparam integer PIXELS_PER_FRAME = SPRITE_W * SPRITE_H;")
    lines.append(f"    localparam integer TOTAL_PIXELS = {total_pixels};")
    lines.append("")
    lines.append("    reg        alpha_rom [0:TOTAL_PIXELS-1];")
    lines.append("    reg [11:0] rgb_rom   [0:TOTAL_PIXELS-1];")
    lines.append("    integer i;")
    lines.append("")
    lines.append("    initial begin")
    lines.append("        for (i = 0; i < TOTAL_PIXELS; i = i + 1) begin")
    lines.append("            alpha_rom[i] = 1'b0;")
    lines.append("            rgb_rom[i] = 12'h000;")
    lines.append("        end")

    for skin_index, (name, frames) in enumerate(skins):
        lines.append(f"        // skin {skin_index}: {name}")
        loaded = [load_frame(frame) for frame in frames]
        for frame_slot in range(MAX_FRAMES):
            src_pixels = loaded[frame_slot % len(loaded)]
            base = (skin_index * MAX_FRAMES + frame_slot) * pixels_per_frame
            for x, y, rgb444 in src_pixels:
                addr = base + y * SPRITE_W + x
                lines.append(f"        alpha_rom[{addr}] = 1'b1; rgb_rom[{addr}] = 12'h{rgb444:03X};")

    lines.append("    end")
    lines.append("")
    lines.append("    wire valid_skin = skin_id < SKIN_COUNT_VALUE;")
    lines.append("    wire [15:0] skin_base = skin_id * MAX_FRAMES * PIXELS_PER_FRAME;")
    lines.append("    wire [15:0] frame_base = frame_index * PIXELS_PER_FRAME;")
    lines.append("    wire [15:0] row_base = sprite_y * SPRITE_W;")
    lines.append("    wire [15:0] addr = skin_base + frame_base + row_base + sprite_x;")
    lines.append("")
    lines.append("    always @(*) begin")
    lines.append("        if (valid_skin && sprite_x < SPRITE_W_VALUE && sprite_y < SPRITE_H_VALUE) begin")
    lines.append("            alpha = alpha_rom[addr];")
    lines.append("            rgb = rgb_rom[addr];")
    lines.append("        end else begin")
    lines.append("            alpha = 1'b0;")
    lines.append("            rgb = 12'h000;")
    lines.append("        end")
    lines.append("    end")
    lines.append("endmodule")

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    skins = discover_skins()
    emit_rom(skins)
    print("Generated", OUT_FILE)
    for index, (name, frames) in enumerate(skins):
        print(f"  {index}: {name}, frames={len(frames)}")


if __name__ == "__main__":
    main()
